services:
  - type: web
    name: vu-universe-backend
    runtime: node
    rootDir: backend-nest
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: node dist/src/main.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://bobbyteja4_db_user:4ZltK5qmHHCxuFt6@cluster0.im2uv.mongodb.net/fbn_xai_system?appName=Cluster0
      - key: JWT_SECRET
        value: vu-universe360-secure-jwt-secret-key-2026
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5001"
      - key: USE_MONGODB
        value: "true"
      - key: USE_MYSQL
        value: "false"
